require("plugins.autopairs")
require("plugins.accelerated-jk")
-- require("plugins.vim-closetag")
require("plugins.catppuccin")
require("plugins.neogen")
require("plugins.cmp")
require("plugins.floatterm")
require("plugins.fzf")
-- require("plugins.telescope")
require("plugins.autopairs")
require("plugins.gitsign")
require("plugins.hightlight-colors")
require("plugins.indentline")
require("plugins.mini")
-- require("plugins.nvim-tree")
require("plugins.neo-tree")
require("plugins.tmux-navigation")
require("plugins.todo-comments")
require("plugins.treesitter")
require("plugins.symbols-outline")
-- require("plugins.bufferline")
-- require("plugins.vim-header")
require("plugins.code_runner")
-- require("plugins.penvim")
-- require("plugins.chadtree")
-- require("plugins.fold")
-- require("plugins.nightfox")
-- require("plugins.nvim-cokeline")
-- require("plugins.incline")
require("plugins.navic")
require("plugins.translate")
require("plugins.comment")
require('plugins.notify')
require("lsp")
